development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV["REDIS_URL"] ? "redis" : "async" %>
  url: <%= ENV.fetch("REDIS_URL", "") %>
  channel_prefix: rails_backend_production
